### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by ColtSeavers78** [dr-itz/RedminePlannerPlugin#34]
When migrating the db I get the following error. 

`/redmine-3.0.3/plugins/redmine_agile/lib/redmine_agile/charts/lead_time_chart.rb:70: warning: duplicated key at line 76 ignored: :stagger_x_labels
An error occurred while loading the routes definition of planner plugin (/home/taskforce/redmine-3.0.3/plugins/planner/config/routes.rb): You should not use the `match` method in your router without specifying an HTTP method.
If you want to expose your action to both GET and POST, add `via: [:get, :post]` option.
If you want to expose your action to GET, use `get` in the router:
  Instead of: match "controller#action"
  Do: get "controller#action".`

I am no dev. but I think it will not be so hard to solve the problem. 

Ubuntu 14.04LTS 
Redmine 3.0.3
ruby 2.2.1p85 (2015-02-26 revision 49769) [i686-linux]
Rails 4.2.1

Br!

**Comment by dr-itz** [comment]
I just pushed the necessary changes to support Redmine 3.x. Released as v0.5.
