### ISSUE TITLE
Uninstall doesn't delete css and js call in redmine

### ISSUE THREAD

**Issue by ThierryDaguin** [dr-itz/RedminePlannerPlugin#37]
Hello,

After uninstalling, errors in console :

![image](https://cloud.githubusercontent.com/assets/6197792/9495251/ea865178-4c0a-11e5-88df-b2a2a38e53a2.png)

Could you tell me how to remove css and js call ?
Thanks
Thierry

Redmine v2.6.0

**Comment by dr-itz** [comment]
Did you completely remove the plugin directory plugins/planner? Did you properly restart Redmine, i.e. the web server (whatever you are using to host the application)? That CSS/JS is only injected if code of planner is still active.
