### ISSUE TITLE
Compatible with Redmine 3.3 

### ISSUE THREAD

**Issue by reyeztom** [dr-itz/RedminePlannerPlugin#38]
Is there someone who can make this plugin run on Redmine 3.3?

**Comment by archonwang** [comment]
just for it. 
or anyone could make the patch about it .
I will try this fork to test it could work on Redmine 3.3.
https://github.com/planio-gmbh/RedminePlannerPlugin/tree/planio/3.3

**Comment by reyeztom** [comment]
great!

**Comment by archonwang** [comment]
@reyeztom , 
it seems worked well on Redmine 3.3.x. Could you make some wiki page to explain how to use it. 
Thanks.

**Comment by dr-itz** [comment]
It should work with Redmine 3.3...
